<?php defined('BLUDIT') or die('Bludit CMS.'); ?>
{
    "crea-tu-propio-contenido": {
        "title": "Crea tu propio contenido",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2020-05-25 20:00:25",
        "dateModified": "",
        "allowComments": true,
        "position": 1,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "a8931902499f144f6a7e9b6f83e1e813",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "set-up-your-new-site": {
        "title": "Configure su nuevo sitio",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2020-05-25 19:59:25",
        "dateModified": "",
        "allowComments": true,
        "position": 1,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "b3ab6d67c5e3d2f50b83076987c0baf8",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "follow-bludit": {
        "title": "Sigue Bludit",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2020-05-25 19:58:25",
        "dateModified": "",
        "allowComments": true,
        "position": 1,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "ef51cdf8ae6029c92d39ffbda4196646",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "acerca-de": {
        "title": "Acerca de",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "static",
        "date": "2020-05-25 19:57:25",
        "dateModified": "",
        "allowComments": true,
        "position": 1,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "cdcbd30cd76b834b6b13e6daf2a2a868",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    }
}