<?php defined('BLUDIT') or die('Bludit CMS.'); ?>
{
    "title": "BLUDIT",
    "slogan": "Bienvenido a Bludit",
    "description": "Felicitaciones ha instalado con \u00e9xito Bludit",
    "footer": "Copyright \u00a9 2020",
    "itemsPerPage": 6,
    "language": "es",
    "locale": "es, es_ES, es_AR, es_MX",
    "timezone": "Atlantic\/Canary",
    "theme": "alternative",
    "adminTheme": "booty",
    "homepage": "",
    "pageNotFound": "",
    "uriPage": "\/",
    "uriTag": "\/tag\/",
    "uriCategory": "\/category\/",
    "uriBlog": "",
    "url": "http:\/\/18.130.253.148:8000",
    "emailFrom": "no-reply@18.130.253.148:8000",
    "orderBy": "date",
    "currentBuild": "0",
    "twitter": "https:\/\/twitter.com\/bludit",
    "facebook": "https:\/\/www.facebook.com\/bluditcms",
    "codepen": "",
    "github": "https:\/\/github.com\/bludit",
    "instagram": "",
    "gitlab": "",
    "linkedin": "",
    "dateFormat": "F j, Y",
    "extremeFriendly": true,
    "autosaveInterval": 2,
    "titleFormatHomepage": "{{site-slogan}} | {{site-title}}",
    "titleFormatPages": "{{page-title}} | {{site-title}}",
    "titleFormatCategory": "{{category-name}} | {{site-title}}",
    "titleFormatTag": "{{tag-name}} | {{site-title}}",
    "imageRestrict": true,
    "imageRelativeToAbsolute": false
}